### ISSUE TITLE
dp and do broken

### ISSUE THREAD

**Issue by kurkale6ka** [bfredl/nvim-miniyank#8] opened 2016-12-20 15:05 UTC
As the title says (`nvim -d` related)

**Comment by bfredl** [comment] 2016-12-21 19:59
Cannot reproduce. Are you sure `miniyank` causes the problem? It does not remap `d` in any way, so `dp` and `do` should be unaffected.

**Comment by kurkale6ka** [comment] 2016-12-22 10:11
It does seem related.
As soon as I comment this in my vimrc `Plug 'bfredl/nvim-miniyank', has('nvim') ? {} : { 'on': [] }` and these in `~/.vim/after/plugin/miniyank.vim`:
```viml
" paste
map p <Plug>(miniyank-autoput)
map P <Plug>(miniyank-autoPut)

" cycle
map <c-n> <Plug>(miniyank-cycle)
```
it all works again

**Comment by kurkale6ka** [comment] 2017-01-05 11:52
An update on this:
`do` is actually unaffected which does make sense...

and the line causing the problem is: `map p <Plug>(miniyank-autoput)` in `~/.vim/after/plugin/miniyank.vim`.
So, keeping the plugin enabled doesn't brake anything, it's specifically the map that brakes `dp`

**Comment by bfredl** [comment] 2017-01-12 12:39
Ah, I see the problem is that `map p` maps `p` also in operator-pending mode. (only normal and visual should be mapped). The quick fix is to add `ounmap p` afterwards. Maybe `autoput` could detect operator-pending mode and handle it automatically, I will look into it later.

**Comment by kurkale6ka** [comment] 2017-01-12 19:22
You could use nmap and xmap

**Comment by bfredl** [comment] 2017-03-18 09:51
Should be fixed, please try latest master.

**Closed as completed** 2017-03-18 09:50 UTC
